"""reference link overrides

Revision ID: 6b94b5f62a11
Revises: 9d92ad667b97
Create Date: 2026-09-05 10:24:50.243474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b94b5f62a11'
down_revision: Union[str, None] = '9d92ad667b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_link_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('callout_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['user_documents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'entry_id', 'span_start', 'span_end', name='uq_override')
    )
    op.create_index(op.f('ix_reference_link_overrides_document_id'), 'reference_link_overrides', ['document_id'], unique=False)
    op.create_index(op.f('ix_reference_link_overrides_owner_id'), 'reference_link_overrides', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_link_overrides_owner_id'), table_name='reference_link_overrides')
    op.drop_index(op.f('ix_reference_link_overrides_document_id'), table_name='reference_link_overrides')
    op.drop_table('reference_link_overrides')
    # ### end Alembic commands ###
